name: sfm
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - python=3.9.12
  - pytorch=1.11.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
    - ffmpeg-python==0.2.0
    - geographiclib==2.0
    - open3d==0.15.2
    - opencv-python==4.6.0.66
    - pandas==1.4.2
    - pycolmap==0.2.0
    - pymap3d==2.9.0
    - pyyaml==6.0
    - scipy==1.8.1
    - tqdm==4.64.0
