name: sfm
channels:
  - open3d-admin
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ffmpeg-python=0.2.0
  - geographiclib=2.0
  - open3d=0.11.2
  - opencv=4.5.5
  - pandas=1.4.2
  - pymap3d=2.9.0
  - pyyaml=6.0
  - scipy=1.7.3
  - tqdm=4.64.0
